# -*- coding: utf-8 -*-
"""DSF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_XMh7Yj9bAIz6ALUIHIlbr_FlmDFA3J
"""

# =========================
# CELL 1
# ULTRA GRANULAR JOB CATEGORY MAPPING
# MEMECAH KATEGORI DENGAN "/" MENJADI LEBIH SPESIFIK
# =========================

from google.colab import drive
import os

# =========================
# MOUNT GOOGLE DRIVE
# =========================

try:
    drive.mount("/content/drive", force_remount=True)
    print("Google Drive berhasil ter-mount.")
except Exception as e:
    print("Google Drive gagal ter-mount.")
    print(e)
    raise

import re
import json
import math
import joblib
import shutil
import numpy as np
import pandas as pd

from collections import Counter
from scipy import sparse

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


# =========================
# 1. SETTING FILE GOOGLE DRIVE
# Sesuai folder: Drive Saya > data1
# =========================

DATA_DIR = "/content/drive/MyDrive/data1"

# File dataset kamu di folder data1
INPUT_FILE = os.path.join(DATA_DIR, "datasetfull (3).csv")

OUTPUT_DIR = os.path.join(DATA_DIR, "fase1_ds_artifacts_ultra_granular")

TEST_SIZE = 0.2
RANDOM_STATE = 42

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Input file:", INPUT_FILE)
print("Output folder:", OUTPUT_DIR)

if not os.path.exists(DATA_DIR):
    raise FileNotFoundError(f"Folder tidak ditemukan: {DATA_DIR}")

print("Isi folder data1:")
print(os.listdir(DATA_DIR))

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"File dataset tidak ditemukan: {INPUT_FILE}\n"
        "Cek nama file CSV di folder data1. Kalau namanya beda, ubah INPUT_FILE."
    )


# =========================
# 2. READ CSV SAFE
# =========================

def read_csv_safe(path):
    try:
        return pd.read_csv(path, encoding="utf-8")
    except UnicodeDecodeError:
        return pd.read_csv(path, encoding="latin1")


# =========================
# 3. CLEAN TEXT
# =========================

def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()
    text = re.sub(r"http\S+|www\S+|https\S+", " ", text)
    text = re.sub(r"\S+@\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"#(\w+)", r"\1", text)
    text = re.sub(r"[/|,;:(){}\[\]\n\t]", " ", text)
    text = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff+#.\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def contains_any(text, patterns):
    return any(re.search(pattern, text, flags=re.IGNORECASE) for pattern in patterns)


# =========================
# 4. NORMALISASI NAMA KOLOM
# =========================

def normalize_required_columns(df):
    df.columns = [str(col).strip() for col in df.columns]
    lower_map = {col.lower().strip(): col for col in df.columns}
    rename_map = {}

    title_candidates = [
        "job_title", "job title", "title", "position", "job position",
        "nama pekerjaan", "pekerjaan"
    ]

    desc_candidates = [
        "job_description", "job description", "description", "desc",
        "job_desc", "job desc", "deskripsi", "deskripsi pekerjaan"
    ]

    for candidate in title_candidates:
        if candidate in lower_map:
            rename_map[lower_map[candidate]] = "job_title"
            break

    for candidate in desc_candidates:
        if candidate in lower_map:
            rename_map[lower_map[candidate]] = "job_description"
            break

    df = df.rename(columns=rename_map)

    required_cols = {"job_title", "job_description"}
    missing = required_cols - set(df.columns)

    if missing:
        print("Kolom yang ditemukan:")
        print(df.columns.tolist())
        raise ValueError(
            f"Kolom wajib tidak ditemukan: {missing}. "
            "Pastikan dataset punya kolom job_title dan job_description."
        )

    return df


# =========================
# 5. ULTRA GRANULAR JOB CATEGORY MAPPING
# KATEGORI DIPECAH LEBIH DETAIL
# =========================

def map_job_category(row):
    title = clean_text(row.get("job_title", ""))
    desc = clean_text(row.get("job_description", ""))
    text = f"{title} {desc}"

    # Rule disusun dari yang paling spesifik ke yang lebih umum.
    # Tidak ada fallback Other/General. Kalau tidak cocok, tetap return None.
    title_rules = [
        # =========================
        # DATA / AI
        # =========================
        ("AI/ML Engineering", [
            r"\bmachine learning engineer\b", r"\bml engineer\b", r"\bmlops\b",
            r"\bml ops\b", r"\bai engineer\b", r"\bartificial intelligence engineer\b",
            r"\bdeep learning engineer\b", r"\bcomputer vision engineer\b",
            r"\bnlp engineer\b", r"\bnatural language processing engineer\b",
            r"\bapplied scientist\b",
        ]),
        ("Data Science", [
            r"\bdata scientist\b", r"\bsenior data scientist\b", r"\blead data scientist\b",
            r"\bdata science\b", r"\bresearch scientist\b", r"\bapplied data scientist\b",
        ]),
        ("Business Intelligence", [
            r"\bbusiness intelligence\b", r"\bbi analyst\b", r"\bbi developer\b",
            r"\bbi specialist\b", r"\bbi engineer\b", r"\bpower bi developer\b",
            r"\bpower bi analyst\b", r"\btableau developer\b", r"\btableau analyst\b",
            r"\bdata visualization specialist\b",
        ]),
        ("Data Analyst", [
            r"\bdata analyst\b", r"\bsenior data analyst\b", r"\bjunior data analyst\b",
            r"\bdata analytics analyst\b", r"\bbusiness analyst\b", r"\bsenior business analyst\b",
            r"\banalytics analyst\b", r"\breporting analyst\b", r"\bmis analyst\b",
            r"\bmis executive\b", r"\bmis officer\b", r"\binsight analyst\b",
            r"\bdata specialist\b", r"\bdata analytics\b",
        ]),
        ("Data Engineering", [
            r"\bdata engineer\b", r"\bsenior data engineer\b", r"\bdata engineering\b",
            r"\bbig data engineer\b", r"\betl engineer\b", r"\betl developer\b",
            r"\bdata pipeline engineer\b", r"\bdata warehouse engineer\b",
            r"\bdata platform engineer\b", r"\bbig data\b", r"\bdata warehouse\b",
        ]),
        ("Database Administrator", [
            r"\bdatabase administrator\b", r"\bdba\b", r"\bdb administrator\b",
            r"\bdatabase engineer\b", r"\bsql server administrator\b", r"\boracle dba\b",
            r"\bmysql administrator\b", r"\bpostgresql administrator\b", r"\bsql dba\b",
            r"\bsql developer\b",
        ]),

        # =========================
        # SOFTWARE / IT
        # =========================
        ("Frontend Development", [
            r"\bfrontend developer\b", r"\bfront end developer\b", r"\bfront-end developer\b",
            r"\bfrontend engineer\b", r"\bfront end engineer\b", r"\breact developer\b",
            r"\breactjs developer\b", r"\bvue developer\b", r"\bvuejs developer\b",
            r"\bangular developer\b", r"\bjavascript developer\b", r"\bfrontend\b",
        ]),
        ("Backend Development", [
            r"\bbackend developer\b", r"\bback end developer\b", r"\bback-end developer\b",
            r"\bbackend engineer\b", r"\bback end engineer\b", r"\bnode\.?js developer\b",
            r"\bnodejs developer\b", r"\bphp developer\b", r"\blaravel developer\b",
            r"\bdjango developer\b", r"\bflask developer\b", r"\bruby on rails developer\b",
            r"\b\.net developer\b", r"\basp\.net developer\b", r"\bbackend\b",
        ]),
        ("Full Stack Development", [
            r"\bfull stack developer\b", r"\bfull-stack developer\b", r"\bfullstack developer\b",
            r"\bfull stack engineer\b", r"\bmern stack developer\b", r"\bmean stack developer\b",
            r"\bfull stack\b", r"\bfullstack\b",
        ]),
        ("Web Development", [
            r"\bweb developer\b", r"\bweb application developer\b", r"\bweb engineer\b",
            r"\bweb programmer\b",
        ]),
        ("Mobile Development", [
            r"\bmobile application developer\b", r"\bmobile app developer\b", r"\bmobile developer\b",
            r"\bmobile engineer\b", r"\bandroid developer\b", r"\bandroid engineer\b",
            r"\bios developer\b", r"\bios engineer\b", r"\bflutter developer\b",
            r"\breact native developer\b", r"\bmobile\b",
        ]),
        ("QA Automation", [
            r"\bqa automation engineer\b", r"\btest automation engineer\b", r"\bautomation test engineer\b",
            r"\bautomation tester\b", r"\bselenium tester\b", r"\bselenium automation\b",
            r"\bautomation qa\b",
        ]),
        ("QA Manual Testing", [
            r"\bmanual tester\b", r"\bqa engineer\b", r"\bquality assurance engineer\b",
            r"\bqa analyst\b", r"\bqa tester\b", r"\bqa executive\b",
            r"\bquality assurance\b", r"\bsoftware tester\b", r"\btest engineer\b",
            r"\btest analyst\b", r"\btester\b",
        ]),
        ("Cybersecurity", [
            r"\bcybersecurity\b", r"\bcybersecurity engineer\b", r"\bcybersecurity analyst\b",
            r"\binformation security\b", r"\binfosec\b", r"\bsecurity engineer\b",
            r"\bsecurity analyst\b", r"\bpenetration tester\b", r"\bethical hacker\b",
            r"\bsoc analyst\b",
        ]),
        ("Cloud/DevOps Engineering", [
            r"\bdevops engineer\b", r"\bdevops\b", r"\bsite reliability engineer\b", r"\bsre\b",
            r"\bcloud engineer\b", r"\bcloud architect\b", r"\baws engineer\b",
            r"\bazure engineer\b", r"\bgcp engineer\b", r"\bkubernetes engineer\b",
            r"\bcloud\b",
        ]),
        ("System Administration", [
            r"\bsystem administrator\b", r"\bsysadmin\b", r"\bsystems administrator\b",
            r"\blinux administrator\b", r"\bwindows administrator\b", r"\bsystem engineer\b",
            r"\binfrastructure engineer\b",
        ]),
        ("Network Engineering", [
            r"\bnetwork administrator\b", r"\bnetwork engineer\b", r"\bnetwork architect\b",
            r"\bnetwork specialist\b", r"\bnetwork security engineer\b",
        ]),
        ("ERP Consulting", [
            r"\berp consultant\b", r"\bsap consultant\b", r"\bsap sd consultant\b",
            r"\bsap mm consultant\b", r"\bsap fico consultant\b", r"\bsap abap consultant\b",
            r"\boracle consultant\b", r"\bsalesforce consultant\b", r"\berp\b",
        ]),
        ("IT Consulting", [
            r"\bit consultant\b", r"\btechnology consultant\b", r"\bsoftware consultant\b",
            r"\bsolution consultant\b", r"\bproject consultant\b", r"\bsystem analyst\b",
            r"\bbusiness systems analyst\b", r"\bfunctional consultant\b", r"\btechnical consultant\b",
            r"\btechnical lead\b",
        ]),
        ("IT Support", [
            r"\bit support\b", r"\bit support executive\b", r"\bit executive\b",
            r"\bit senior executive\b", r"\bsenior it executive\b", r"\bit officer\b",
            r"\bit specialist\b", r"\bit assistant\b", r"\bit technician\b",
            r"\btechnical support\b", r"\bhelpdesk\b", r"\bdesktop support\b",
            r"\bapplication support\b", r"\bapplication specialist\b", r"\bsoftware support\b",
            r"\btechnical executive\b", r"\btechnical assistant\b", r"\bservice desk\b",
        ]),
        ("Software Development", [
            r"\bsoftware engineer\b", r"\bsoftware developer\b", r"\bapplication developer\b",
            r"\bprogrammer\b", r"\bjava developer\b", r"\bpython developer\b",
            r"\bc\+\+ developer\b", r"\bc# developer\b", r"\bdeveloper\b",
        ]),

        # =========================
        # FINANCE / ACCOUNTING
        # =========================
        ("Audit", [
            r"\binternal auditor\b", r"\bexternal auditor\b", r"\bsenior auditor\b",
            r"\bauditor\b", r"\baudit manager\b", r"\baudit\b",
        ]),
        ("Tax", [
            r"\btax consultant\b", r"\btax specialist\b", r"\btax manager\b",
            r"\btax accountant\b", r"\btax analyst\b", r"\btax\b",
        ]),
        ("Insurance", [
            r"\binsurance agent\b", r"\binsurance advisor\b", r"\binsurance consultant\b",
            r"\binsurance executive\b", r"\binsurance\b",
        ]),
        ("Banking & Financial Services", [
            r"\bfinancial advisor\b", r"\bfinancial planner\b", r"\bfinancial consultant\b",
            r"\bwealth manager\b", r"\bprivate banker\b", r"\brelationship manager\b",
            r"\bunit trust consultant\b", r"\bmortgage specialist\b", r"\bar rahnu\b",
            r"\bperunding kewangan\b",
        ]),
        ("Accounting", [
            r"\baccountant\b", r"\bsenior accountant\b", r"\baccount executive\b",
            r"\baccounts executive\b", r"\bexecutive accounts\b", r"\bexecutive, accounts\b",
            r"\bsenior account executive\b", r"\bsenior accounts executive\b",
            r"\bjunior account executive\b", r"\bjunior accounts executive\b",
            r"\baccount assistant\b", r"\baccounts assistant\b", r"\baccount officer\b",
            r"\baccounts officer\b", r"\baccount payable\b", r"\baccounts payable\b",
            r"\baccount receivable\b", r"\baccounts receivable\b", r"\bbookkeeper\b",
            r"\baccounting\b", r"\baccount assistance\b", r"\baccount\b",
        ]),
        ("Finance", [
            r"\bfinance manager\b", r"\bcfo\b", r"\bfinancial analyst\b",
            r"\bfinancial controller\b", r"\btreasury\b", r"\bpayroll\b",
            r"\bcredit control\b", r"\bcredit controller\b", r"\bfinance\b",
            r"\bcosting executive\b", r"\bpricing executive\b", r"\bbilling\b", r"\binvoice\b",
        ]),

        # =========================
        # SALES / CUSTOMER
        # =========================
        ("Real Estate Sales", [
            r"\breal estate\b", r"\bproperty agent\b", r"\bnegotiator\b",
        ]),
        ("Telesales", [r"\btelesales\b", r"\btelemarketing\b"]),
        ("Business Development", [
            r"\bbusiness development\b", r"\bbd executive\b", r"\bpartnership manager\b",
        ]),
        ("Sales", [
            r"\bsales executive\b", r"\bsenior sales executive\b", r"\bcorporate sales executive\b",
            r"\bsales coordinator\b", r"\bsales assistant\b", r"\bsales representative\b",
            r"\bmedical sales representative\b", r"\bsales consultant\b", r"\bsales engineer\b",
            r"\bkey account executive\b", r"\bretail associate\b", r"\bretail sales\b",
            r"\bsales manager\b", r"\bsales\b",
        ]),
        ("Customer Service", [
            r"\bcustomer service\b", r"\bcustomer support\b", r"\bcustomer success\b",
            r"\bcall center\b", r"\bclient service\b", r"客服",
            r"\bcustomer care\b", r"\bcustomer care executive\b", r"\bservice advisor\b",
            r"\bclient servicing\b", r"\bfront desk\b",
        ]),

        # =========================
        # MARKETING / CREATIVE
        # =========================
        ("Digital Marketing", [
            r"\bdigital marketing\b", r"\bseo\b", r"\bsem\b", r"\bsocial media\b",
            r"\be-commerce\b", r"\becommerce\b", r"\be-commerce executive\b",
            r"\becommerce executive\b", r"\bmarketplace specialist\b",
        ]),
        ("Content & Copywriting", [
            r"\bcontent creator\b", r"\bcontent writer\b", r"\bcopywriter\b",
            r"\bcontent strategist\b", r"\bwriter\b", r"\btranslator\b",
        ]),
        ("Public Relations & Events", [
            r"\bpublic relations\b", r"\bpr executive\b", r"\bevent coordinator\b",
            r"\bevent manager\b", r"\bevent executive\b", r"\bcommunications\b",
            r"\blive host\b", r"\btiktok live host\b",
        ]),
        ("Marketing", [
            r"\bmarketing executive\b", r"\bsenior marketing executive\b", r"\bmarketing manager\b",
            r"\bsales & marketing executive\b", r"\bbrand manager\b", r"\bbrand executive\b",
            r"\bproduct marketing\b", r"\bvisual merchandiser\b", r"\bmerchandiser\b",
            r"\bstore executive\b", r"\bmarketing\b",
        ]),
        ("UX Design & Research", [
            r"\bux designer\b", r"\bux researcher\b", r"\buser experience\b",
            r"\bproduct designer\b",
        ]),
        ("UI Design", [r"\bui designer\b", r"\buser interface designer\b"]),
        ("Video Production", [
            r"\bvideo editor\b", r"\bvideographer\b", r"\bvideo producer\b",
            r"\bmotion graphics\b", r"\banimator\b",
        ]),
        ("Multimedia Design", [
            r"\bmultimedia designer\b", r"\bmultimedia specialist\b", r"\bmultimedia\b",
        ]),
        ("Graphic Design", [
            r"\bgraphic designer\b", r"\bcreative designer\b", r"\bvisual designer\b",
            r"\bart director\b", r"\bdesigner\b",
        ]),

        # =========================
        # HR / ADMIN
        # =========================
        ("Training & Development", [
            r"\btrainer\b", r"\btraining manager\b", r"\btraining executive\b",
            r"\btraining & development executive\b", r"\btraining and development executive\b",
            r"\btraining coordinator\b", r"\blearning development\b",
            r"\blearning and development\b", r"\bl&d\b", r"\btalent development\b",
        ]),
        ("Recruitment", [r"\brecruiter\b", r"\btalent acquisition\b", r"\brecruitment\b"]),
        ("HR Operations", [
            r"\bhr manager\b", r"\bhr executive\b", r"\bhuman resources\b", r"\bhrbp\b",
            r"\bhr\b", r"\bhuman resource executive\b", r"\bsenior human resource executive\b",
            r"\bhuman resource assistant\b", r"\bhuman resource officer\b", r"\bhuman resource\b",
        ]),
        ("Reception", [r"\breceptionist\b"]),
        ("Executive Assistant", [
            r"\bpersonal assistant\b", r"\bexecutive assistant\b", r"\bsecretary\b",
            r"\bdocument controller\b", r"\bdocument control\b",
        ]),
        ("Administration", [
            r"\badministration\b", r"\badministrative\b", r"\badmin\b",
            r"\boffice assistant\b", r"\bclerk\b", r"\bdata entry\b",
            r"\badministrator\b", r"\boffice administrator\b", r"\badministration executive\b",
            r"\bexecutive, administration\b", r"\bexecutive administration\b",
            r"\bsenior executive, administration\b", r"\badministration assistant\b",
            r"\badministrative executive\b", r"\badministrative assistant\b", r"\badministration officer\b",
            r"\bcontract executive\b",
        ]),

        # =========================
        # OPERATIONS / SUPPLY CHAIN
        # =========================
        ("Procurement", [
            r"\bprocurement\b", r"\bpurchasing\b", r"\bpurchaser\b", r"\bbuyer\b",
            r"\bsourcing\b", r"\bsupply chain\b", r"\bpurchase executive\b",
            r"\bpurchasing executive\b", r"\bprocurement executive\b",
        ]),
        ("Warehouse Operations", [
            r"\bwarehouse\b", r"\bwarehouse assistant\b", r"\bwarehouse executive\b",
            r"\bstorekeeper\b", r"\bstore assistant\b", r"\bmaterial handler\b",
        ]),
        ("Logistics", [
            r"\blogistics\b", r"\blogistic executive\b", r"\blogistic assistant\b",
            r"\blogistic officer\b", r"\blogistic coordinator\b", r"\bshipping\b", r"\bdispatch\b",
        ]),
        ("Planning & Operations", [
            r"\binventory\b", r"\bplanner\b", r"\boperation executive\b",
            r"\boperations executive\b", r"\boperation assistant\b", r"\boperations assistant\b",
            r"\boperation coordinator\b", r"\boperations coordinator\b", r"\bexecutive operations\b",
            r"\bexecutive - operations\b", r"\bplanning\b",
        ]),
        ("Transport & Fleet", [r"\bfleet\b", r"\btransport\b", r"\bdriver\b"]),
        ("Facilities Management", [r"\bfacilities\b", r"\bfacility\b"]),
        ("Property Management", [
            r"\bproperty executive\b", r"\bproperty officer\b", r"\bleasing\b",
        ]),

        # =========================
        # ENGINEERING / TECHNICAL
        # =========================
        ("Project Management", [
            r"\bproject manager\b", r"\bproject coordinator\b", r"\bproject engineer\b",
            r"\bproject executive\b", r"\bproject assistant\b", r"\bproject scheduler\b",
            r"\bproject leader\b", r"\bscrum master\b", r"\bproduct manager\b",
        ]),
        ("Construction & Site", [
            r"\bquantity surveyor\b", r"\bsite engineer\b", r"\bsite supervisor\b",
            r"\bconstruction\b", r"\barchitect\b", r"\bsurveyor\b",
            r"\binspector of works\b", r"\binspector of work\b",
        ]),
        ("Technical Trades", [
            r"\bdrafter\b", r"\bdraughtsman\b", r"\bdraftsman\b", r"\bdraftsperson\b",
            r"\bdraughtsperson\b", r"\bm&e coordinator\b", r"\bmechanical & electrical coordinator\b",
            r"\belectrician\b", r"\bchargeman\b", r"\bforeman\b", r"\bwelder\b",
            r"\bmechanic\b", r"\bmekanik\b", r"\bcarpenter\b", r"\bbim modeller\b",
            r"\bbim modeler\b", r"\bcnc machinist\b", r"\bhandyman\b", r"\bwireman\b",
            r"\bboilerman\b", r"\bmaterial handler\b",
        ]),
        ("Engineering", [
            r"\bservice engineer\b", r"\bcivil engineer\b", r"\bmechanical engineer\b",
            r"\belectrical engineer\b", r"\bengineer\b",
        ]),

        # =========================
        # MANUFACTURING / HEALTH / LEGAL / HOSPITALITY
        # =========================
        ("Quality Control", [
            r"\bquality control\b", r"\bqc inspector\b", r"\bquality assurance\b",
            r"\bqa inspector\b", r"\bqc\b",
        ]),
        ("R&D", [
            r"\br&d\b", r"\br&d executive\b", r"\br&d chemist\b",
            r"\bresearch development\b", r"\bresearch scientist\b", r"\bresearch analyst\b",
            r"\bresearch executive\b", r"\bchemist\b",
        ]),
        ("Product Development", [
            r"\bproduct development\b", r"\bproduct specialist\b", r"\bproduct executive\b",
        ]),
        ("Maintenance", [r"\bmaintenance\b", r"\btechnician\b"]),
        ("Production", [r"\bproduction\b", r"\bmanufacturing\b", r"\boperator\b"]),
        ("Education", [
            r"\bteacher\b", r"\bguru\b", r"\blecturer\b", r"\btutor\b", r"\binstructor\b", r"幼儿园老师",
        ]),
        ("Healthcare", [
            r"\bdoctor\b", r"\bnurse\b", r"\bmedical\b", r"\bpharmacist\b",
            r"\bpharmacy assistant\b", r"\btherapist\b", r"\bdental\b",
            r"\bphysiotherapist\b", r"\bclinic assistant\b", r"\bclinic\b",
            r"\bradiographer\b", r"\bcaregiver\b", r"\bnutritionist\b", r"\bbeautician\b",
            r"\boptometrist\b",
        ]),
        ("Safety & HSE", [
            r"\bhse\b", r"\behs executive\b", r"\bsafety officer\b", r"\benvironmental officer\b",
            r"\bsafety and health officer\b", r"\bsafety & health officer\b",
            r"\bsafety health officer\b", r"\bsafety executive\b", r"\bsafety coordinator\b",
        ]),
        ("Compliance", [r"\bcompliance\b", r"\bregulatory\b"]),
        ("Legal", [r"\blawyer\b", r"\blegal\b", r"\bparalegal\b"]),
        ("Company Secretarial", [
            r"\bcompany secretary\b", r"\bcompany secretarial\b",
            r"\bcompany secretarial assistant\b", r"\bcorporate secretarial\b",
            r"\bcorporate secretarial assistant\b",
        ]),
        ("Hospitality", [
            r"\bhotel\b", r"\bhospitality\b", r"\bhousekeeping\b", r"\bexecutive housekeeper\b",
        ]),
        ("Food & Beverage", [
            r"\bchef\b", r"\bcook\b", r"\bkitchen\b", r"\bf&b\b", r"\bbarista\b",
            r"\bwaiter\b", r"\bwaitress\b", r"\bwaiter/waitress\b",
        ]),
        ("Security", [r"\bsecurity\b"]),
        ("Cleaning", [r"\bcleaner\b"]),
        ("Skilled Worker", [r"\bstore assistant\b", r"\bpekerja am\b"]),
        ("Internship", [r"\bintern\b", r"\binternship\b", r"\btrainee\b", r"\bprotege\b"]),
        ("Management", [
            r"\bceo\b", r"\bcoo\b", r"\bcto\b", r"\bcfo\b", r"\bdirector\b",
            r"\bgeneral manager\b", r"\bmanager\b", r"\bsupervisor\b", r"\bteam lead\b",
            r"\bhead of\b",
        ]),
    ]

    for category, patterns in title_rules:
        if contains_any(title, patterns):
            return category

    desc_rules = [
        ("AI/ML Engineering", [r"\bmachine learning model deployment\b", r"\bml pipeline\b", r"\bmodel serving\b"]),
        ("Data Science", [r"\bpredictive modeling\b", r"\bstatistical analysis\b", r"\bdata science research\b"]),
        ("Business Intelligence", [r"\bpower bi dashboard\b", r"\btableau visualization\b", r"\bbi reporting\b"]),
        ("Data Analyst", [r"\bdata analysis\b", r"\breporting\b", r"\bexcel analysis\b"]),
        ("Accounting", [r"\bfull set of accounts\b", r"\baccount payable\b", r"\baccount receivable\b", r"\breconciliation\b"]),
        ("Finance", [r"\bfinancial reporting\b", r"\btreasury\b", r"\bcredit control\b"]),
        ("Customer Service", [r"\bcustomer enquiries\b", r"\bcustomer complaints\b", r"\bcustomer support\b", r"\bcustomer service\b"]),
        ("Procurement", [r"\bprocurement process\b", r"\bpurchase order\b"]),
        ("Logistics", [r"\bwarehouse management\b", r"\blogistics operation\b"]),
        ("Digital Marketing", [r"\bsocial media campaign\b", r"\bdigital marketing\b", r"\bseo\b", r"\bsem\b", r"\bcontent creation\b"]),
    ]

    for category, patterns in desc_rules:
        if contains_any(desc, patterns):
            return category

    return None


# =========================
# 6. SKILL EXTRACTION
# =========================

SKILL_TAXONOMY = {
    "Python": [r"\bpython\b"],
    "R": [r"\br programming\b", r"\br language\b"],
    "SQL": [r"\bsql\b", r"\bmysql\b", r"\bpostgresql\b"],
    "Java": [r"\bjava\b"],
    "JavaScript": [r"\bjavascript\b", r"\bnode\.?js\b", r"\breact\b"],
    "PHP": [r"\bphp\b", r"\blaravel\b"],
    "Excel": [r"\bexcel\b", r"\bvlookup\b", r"\bpivot table\b"],
    "Machine Learning": [r"\bmachine learning\b", r"\bml\b"],
    "Deep Learning": [r"\bdeep learning\b", r"\bneural network\b"],
    "NLP": [r"\bnlp\b", r"\bnatural language processing\b"],
    "Computer Vision": [r"\bcomputer vision\b"],
    "TensorFlow": [r"\btensorflow\b"],
    "PyTorch": [r"\bpytorch\b"],
    "Scikit-learn": [r"\bscikit[- ]learn\b"],
    "Pandas": [r"\bpandas\b"],
    "NumPy": [r"\bnumpy\b"],
    "Power BI": [r"\bpower bi\b"],
    "Tableau": [r"\btableau\b"],
    "Spark": [r"\bspark\b"],
    "Hadoop": [r"\bhadoop\b"],
    "Kafka": [r"\bkafka\b"],
    "AWS": [r"\baws\b", r"\bamazon web services\b"],
    "Azure": [r"\bazure\b"],
    "GCP": [r"\bgcp\b", r"\bgoogle cloud\b"],
    "Docker": [r"\bdocker\b"],
    "Kubernetes": [r"\bkubernetes\b", r"\bk8s\b"],
    "CI/CD": [r"\bci/cd\b", r"\bjenkins\b"],
    "Git": [r"\bgit\b", r"\bgithub\b"],
    "Data Analysis": [r"\bdata analysis\b", r"\banalytical\b"],
    "Data Visualization": [r"\bdata visualization\b", r"\bdashboard\b"],
    "Statistics": [r"\bstatistics\b", r"\bstatistical\b"],
    "Marketing": [r"\bmarketing\b"],
    "SEO": [r"\bseo\b"],
    "Social Media": [r"\bsocial media\b"],
    "Sales": [r"\bsales\b", r"\bnegotiation\b"],
    "Customer Service": [r"\bcustomer service\b"],
    "Leadership": [r"\bleadership\b", r"\bteam management\b"],
    "Communication": [r"\bcommunication\b"],
    "Project Management": [r"\bproject management\b", r"\bagile\b"],
}


def extract_skills(text):
    if pd.isna(text):
        text = ""
    text = str(text).lower()
    found = []
    for skill, patterns in SKILL_TAXONOMY.items():
        if contains_any(text, patterns):
            found.append(skill)
    return found


# =========================
# 7. HELPER FUNCTIONS
# =========================

def can_use_stratify(y, test_size):
    counts = Counter(y)
    if len(counts) < 2:
        return False
    if min(counts.values()) < 2:
        return False
    n_test = math.ceil(len(y) * test_size)
    n_train = len(y) - n_test
    if n_test < len(counts) or n_train < len(counts):
        return False
    return True


def class_distribution(y_values, label_encoder):
    counter = Counter(y_values)
    distribution = {}
    for encoded_label, count in counter.items():
        class_name = label_encoder.inverse_transform([encoded_label])[0]
        distribution[class_name] = int(count)
    return dict(sorted(distribution.items(), key=lambda item: item[1], reverse=True))


# =========================
# 8. TESTING FUNCTION
# =========================

def test_job_mapping(test_cases):
    print("\n" + "="*80)
    print("TESTING ULTRA GRANULAR JOB CATEGORY MAPPING")
    print("="*80)

    correct = 0
    total = len(test_cases)
    results = []

    for i, case in enumerate(test_cases, 1):
        row = {
            "job_title": case.get("title", ""),
            "job_description": case.get("description", "")
        }

        predicted = map_job_category(row)
        expected = case.get("expected_category", None)

        is_correct = (predicted == expected)
        if is_correct:
            correct += 1
            status = "✓ CORRECT"
        else:
            status = "✗ WRONG"

        results.append({
            "no": i,
            "title": case.get("title", ""),
            "expected": expected,
            "predicted": predicted,
            "status": status
        })

        print(f"\n{i}. {status}")
        print(f"   Title: {case.get('title', '')}")
        print(f"   Expected: {expected}")
        print(f"   Predicted: {predicted}")

    accuracy = (correct / total * 100) if total > 0 else 0

    print("\n" + "="*80)
    print(f"MAPPING ACCURACY: {correct}/{total} ({accuracy:.2f}%)")
    print("="*80)

    return pd.DataFrame(results)


# =========================
# 9. MAIN PIPELINE
# =========================

def run_pipeline_csv(input_file, output_dir, test_size=0.2, random_state=42):
    os.makedirs(output_dir, exist_ok=True)

    df_raw = read_csv_safe(input_file)
    df_raw = normalize_required_columns(df_raw)

    print("Kolom yang ditemukan:")
    print(df_raw.columns.tolist())

    total_before = len(df_raw)

    df_raw["job_title"] = df_raw["job_title"].fillna("").astype(str).str.strip()
    df_raw["job_description"] = df_raw["job_description"].fillna("").astype(str)

    empty_title_mask = (
        (df_raw["job_title"] == "") |
        (df_raw["job_title"].str.lower() == "nan")
    )

    removed_rows_empty_job_title = int(empty_title_mask.sum())
    df_raw = df_raw[~empty_title_mask].reset_index(drop=True)

    invalid_title_mask = df_raw["job_title"].str.contains(
        r"\bmctf\b|exhibition centre|career fair",
        case=False,
        na=False
    )

    removed_invalid_titles = int(invalid_title_mask.sum())
    df_raw = df_raw[~invalid_title_mask].reset_index(drop=True)

    total_after_title_filter = len(df_raw)

    print(f"\n[INFO] Jumlah data awal: {total_before}")
    print(f"[INFO] Dibuang karena job_title kosong: {removed_rows_empty_job_title}")
    print(f"[INFO] Dibuang karena bukan job title valid: {removed_invalid_titles}")
    print(f"[INFO] Setelah filter awal: {total_after_title_filter}")

    if len(df_raw) == 0:
        raise ValueError("Dataset kosong setelah menghapus job_title kosong / tidak valid.")

    df_raw["clean_text"] = (
        df_raw["job_title"].fillna("").astype(str) + " " +
        df_raw["job_description"].fillna("").astype(str)
    ).apply(clean_text)

    df_raw["job_title_normalized"] = df_raw["job_title"].apply(clean_text)

    print("\n[INFO] Mulai mapping job_category...")
    df_raw["job_category"] = df_raw.apply(map_job_category, axis=1)

    unmapped_rows = df_raw[df_raw["job_category"].isna()].copy()
    mapped_rows = df_raw[df_raw["job_category"].notna()].copy()

    unmapped_rows[["job_title", "job_description"]].to_csv(
        os.path.join(output_dir, "cek_unmapped_rows.csv"),
        index=False,
        encoding="utf-8"
    )

    print("\n[INFO] Jumlah data belum ter-mapping:", len(unmapped_rows))
    print("[INFO] Persentase belum ter-mapping:", round(len(unmapped_rows) / len(df_raw) * 100, 2), "%")

    print("\n[INFO] Top 50 job_title yang belum ter-mapping:")
    if len(unmapped_rows) > 0:
        unmapped_titles = unmapped_rows["job_title"].value_counts().head(50)
        print(unmapped_titles)
        unmapped_titles.to_csv(
            os.path.join(output_dir, "top_unmapped_titles.csv"),
            header=["count"],
            encoding="utf-8"
        )
    else:
        print("Tidak ada data unmapped.")

    df = mapped_rows.reset_index(drop=True)

    if len(df) == 0:
        raise ValueError("Tidak ada data yang berhasil dipetakan.")

    print("\n[INFO] Jumlah data yang dipakai training:", len(df))
    print("[INFO] Jumlah data yang tidak dipakai training:", len(unmapped_rows))

    print("\n[INFO] Distribusi job_category:")
    category_dist = df["job_category"].value_counts()
    print(category_dist)

    print("\n[INFO] Persentase job_category:")
    category_pct = (df["job_category"].value_counts(normalize=True) * 100).round(2)
    print(category_pct)

    pd.DataFrame({
        "job_category": category_dist.index,
        "count": category_dist.values,
        "percentage": category_pct.values
    }).to_csv(
        os.path.join(output_dir, "category_distribution.csv"),
        index=False,
        encoding="utf-8"
    )

    text_for_skills = (
        df["job_title"].fillna("").astype(str) + " " +
        df["job_description"].fillna("").astype(str) + " " +
        df["clean_text"].fillna("").astype(str)
    )

    print("\n[INFO] Extracting skills...")
    df["skills_extracted"] = text_for_skills.apply(extract_skills)

    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(df["job_category"])

    df["job_category_encoded"] = y

    indices = np.arange(len(df))
    stratify = y if can_use_stratify(y, test_size) else None

    print("\n[INFO] Splitting data...")
    train_idx, test_idx = train_test_split(
        indices,
        test_size=test_size,
        random_state=random_state,
        stratify=stratify
    )

    df["split"] = "test"
    df.loc[train_idx, "split"] = "train"

    train_texts = df.loc[train_idx, "clean_text"].fillna("").astype(str).tolist()
    test_texts = df.loc[test_idx, "clean_text"].fillna("").astype(str).tolist()
    all_texts = df["clean_text"].fillna("").astype(str).tolist()

    train_texts = [text if text.strip() else "emptytext" for text in train_texts]
    test_texts = [text if text.strip() else "emptytext" for text in test_texts]
    all_texts = [text if text.strip() else "emptytext" for text in all_texts]

    print("\n[INFO] Vectorizing with TF-IDF...")
    vectorizer = TfidfVectorizer(
        max_features=8000,
        ngram_range=(1, 2),
        min_df=1,
        sublinear_tf=True
    )

    X_train = vectorizer.fit_transform(train_texts)
    X_test = vectorizer.transform(test_texts)
    X_all = vectorizer.transform(all_texts)

    y_train = y[train_idx]
    y_test = y[test_idx]

    df_output = df.copy()

    df_output["skills_extracted"] = df_output["skills_extracted"].apply(
        lambda x: ", ".join(x) if len(x) > 0 else "[]"
    )

    print("\n[INFO] Saving processed data...")
    df_output.to_csv(os.path.join(output_dir, "processed_data.csv"), index=False, encoding="utf-8")
    df_output.to_csv(os.path.join(output_dir, "processed_data_category.csv"), index=False, encoding="utf-8")

    sparse.save_npz(os.path.join(output_dir, "X_tfidf_all.npz"), X_all)
    sparse.save_npz(os.path.join(output_dir, "X_train_tfidf.npz"), X_train)
    sparse.save_npz(os.path.join(output_dir, "X_test_tfidf.npz"), X_test)

    np.save(os.path.join(output_dir, "y_all.npy"), y)
    np.save(os.path.join(output_dir, "y_train.npy"), y_train)
    np.save(os.path.join(output_dir, "y_test.npy"), y_test)

    joblib.dump(vectorizer, os.path.join(output_dir, "tfidf_vectorizer.pkl"))
    joblib.dump(label_encoder, os.path.join(output_dir, "label_encoder_category.pkl"))

    label_mapping = pd.DataFrame({
        "job_category": label_encoder.classes_,
        "job_category_encoded": range(len(label_encoder.classes_))
    })

    label_mapping.to_csv(
        os.path.join(output_dir, "job_category_label_mapping.csv"),
        index=False,
        encoding="utf-8"
    )

    split_info = pd.DataFrame({
        "row_index_zero_based": np.arange(len(df)),
        "split": df["split"]
    })

    split_info.to_csv(
        os.path.join(output_dir, "train_test_indices.csv"),
        index=False,
        encoding="utf-8"
    )

    summary = {
        "input_file": input_file,
        "output_dir": output_dir,
        "total_rows_before_filter": int(total_before),
        "removed_rows_empty_job_title": int(removed_rows_empty_job_title),
        "removed_invalid_titles": int(removed_invalid_titles),
        "total_rows_after_initial_filter": int(total_after_title_filter),
        "mapped_rows_used_for_training": int(len(df)),
        "unmapped_rows_not_used_for_training": int(len(unmapped_rows)),
        "unmapped_percentage_from_clean_data": float(round(len(unmapped_rows) / len(df_raw) * 100, 2)),
        "target_column": "job_category",
        "category_granularity": "ULTRA GRANULAR - Categories with / split into separate classes",
        "total_classes": int(len(label_encoder.classes_)),
        "label_classes": label_encoder.classes_.tolist(),
        "stratify_used": bool(stratify is not None),
        "tfidf_all_shape": list(X_all.shape),
        "train_shape": list(X_train.shape),
        "test_shape": list(X_test.shape),
        "train_class_distribution": class_distribution(y_train, label_encoder),
        "test_class_distribution": class_distribution(y_test, label_encoder),
        "note": (
            "ULTRA GRANULAR VERSION: Categories with / are split into more specific classes. "
            "Examples: Data Science / AI → Data Science + AI/ML Engineering. "
            "Data Analyst / BI → Data Analyst + Business Intelligence. "
            "This provides more precise categorization for specialized roles."
        )
    }

    with open(os.path.join(output_dir, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    zip_path = output_dir + ".zip"

    if os.path.exists(zip_path):
        os.remove(zip_path)

    shutil.make_archive(output_dir, "zip", output_dir)

    print("\n==============================")
    print("PIPELINE SELESAI")
    print("==============================")
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print("\nFolder hasil:", output_dir)
    print("ZIP hasil:", zip_path)

    return df_output, summary


# =========================
# 10. RUN WITH TESTING
# =========================

test_cases = [
    {"title": "Data Scientist", "description": "", "expected_category": "Data Science"},
    {"title": "Machine Learning Engineer", "description": "", "expected_category": "AI/ML Engineering"},
    {"title": "Data Analyst", "description": "", "expected_category": "Data Analyst"},
    {"title": "Business Intelligence Analyst", "description": "", "expected_category": "Business Intelligence"},
    {"title": "Power BI Developer", "description": "", "expected_category": "Business Intelligence"},
    {"title": "Frontend Developer", "description": "", "expected_category": "Frontend Development"},
    {"title": "Backend Developer", "description": "", "expected_category": "Backend Development"},
    {"title": "Full Stack Developer", "description": "", "expected_category": "Full Stack Development"},
    {"title": "QA Automation Engineer", "description": "", "expected_category": "QA Automation"},
    {"title": "Manual Tester", "description": "", "expected_category": "QA Manual Testing"},
    {"title": "DevOps Engineer", "description": "", "expected_category": "Cloud/DevOps Engineering"},
    {"title": "System Administrator", "description": "", "expected_category": "System Administration"},
    {"title": "Network Engineer", "description": "", "expected_category": "Network Engineering"},
    {"title": "Auditor", "description": "", "expected_category": "Audit"},
    {"title": "Tax Consultant", "description": "", "expected_category": "Tax"},
    {"title": "Insurance Agent", "description": "", "expected_category": "Insurance"},
    {"title": "Financial Advisor", "description": "", "expected_category": "Banking & Financial Services"},
    {"title": "Recruiter", "description": "", "expected_category": "Recruitment"},
    {"title": "HR Executive", "description": "", "expected_category": "HR Operations"},
    {"title": "Trainer", "description": "", "expected_category": "Training & Development"},
]

test_results = test_job_mapping(test_cases)

df_result, summary = run_pipeline_csv(
    input_file=INPUT_FILE,
    output_dir=OUTPUT_DIR,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE
)

print("\n[SUCCESS] Pipeline Cell 1 selesai!")
df_result.head()

# =========================
# CELL 2
# TRAINING MODEL + EVALUATION + DOWNLOAD ZIP FINAL
# Untuk kategori paling kerucut
# Dataset: /content/drive/MyDrive/data1/datasetfull (3).csv
# =========================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from scipy import sparse
import numpy as np
import pandas as pd
import joblib
import os
import json
import shutil
from google.colab import files


# =========================
# 1. SETTING OUTPUT FOLDER
# Harus sama dengan OUTPUT_DIR di Cell 1
# =========================

OUTPUT_DIR = "/content/drive/MyDrive/data1/fase1_ds_artifacts_ultra_granular"


# =========================
# 2. CEK FILE HASIL CELL 1
# =========================

required_files = [
    "X_train_tfidf.npz",
    "X_test_tfidf.npz",
    "y_train.npy",
    "y_test.npy",
    "label_encoder_category.pkl",
    "tfidf_vectorizer.pkl",
    "processed_data_category.csv",
    "summary.json"
]

missing_files = [
    filename for filename in required_files
    if not os.path.exists(os.path.join(OUTPUT_DIR, filename))
]

if missing_files:
    raise FileNotFoundError(
        "File hasil Cell 1 belum lengkap. Jalankan Cell 1 dulu sampai selesai.\n"
        f"File yang belum ada: {missing_files}"
    )

print("[INFO] Semua file dari Cell 1 ditemukan.")
print("[INFO] Output folder:", OUTPUT_DIR)


# =========================
# 3. LOAD DATA TRAINING
# =========================

X_train = sparse.load_npz(os.path.join(OUTPUT_DIR, "X_train_tfidf.npz"))
X_test = sparse.load_npz(os.path.join(OUTPUT_DIR, "X_test_tfidf.npz"))

y_train = np.load(os.path.join(OUTPUT_DIR, "y_train.npy"))
y_test = np.load(os.path.join(OUTPUT_DIR, "y_test.npy"))

label_encoder = joblib.load(os.path.join(OUTPUT_DIR, "label_encoder_category.pkl"))

print("\n[INFO] Shape X_train:", X_train.shape)
print("[INFO] Shape X_test :", X_test.shape)
print("[INFO] Jumlah y_train:", len(y_train))
print("[INFO] Jumlah y_test :", len(y_test))
print("[INFO] Total kelas:", len(label_encoder.classes_))

if X_train.shape[0] != len(y_train):
    raise ValueError("Jumlah baris X_train tidak sama dengan y_train.")

if X_test.shape[0] != len(y_test):
    raise ValueError("Jumlah baris X_test tidak sama dengan y_test.")


# =========================
# 4. TRAIN MODEL
# =========================

model = LogisticRegression(
    max_iter=5000,
    class_weight=None,
    C=2.0,
    solver="lbfgs",
    random_state=42,
    n_jobs=-1
)

print("\n[INFO] Mulai training model...")
model.fit(X_train, y_train)
print("[INFO] Training selesai.")


# =========================
# 5. EVALUATION
# =========================

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

report_dict = classification_report(
    y_test,
    y_pred,
    labels=np.arange(len(label_encoder.classes_)),
    target_names=label_encoder.classes_,
    zero_division=0,
    output_dict=True
)

report_text = classification_report(
    y_test,
    y_pred,
    labels=np.arange(len(label_encoder.classes_)),
    target_names=label_encoder.classes_,
    zero_division=0
)

print("\nClassification Report:")
print(report_text)


# =========================
# 6. SAVE MODEL DAN REPORT
# =========================

# model_path = os.path.join(OUTPUT_DIR, "logistic_regression_model.pkl")
# joblib.dump(model, model_path)

# print("\n[SISTEM] Model berhasil disimpan:")
# print(model_path)

# report_df = pd.DataFrame(report_dict).transpose()
# report_csv_path = os.path.join(OUTPUT_DIR, "classification_report.csv")
# report_df.to_csv(report_csv_path, index=True, encoding="utf-8")

# print("\n[SISTEM] Classification report berhasil disimpan:")
# print(report_csv_path)

# metrics = {
#     "accuracy": float(accuracy),
#     "total_classes": int(len(label_encoder.classes_)),
#     "classes": label_encoder.classes_.tolist(),
#     "model": "LogisticRegression",
#     "max_iter": 5000,
#     "class_weight": None,
#     "C": 2.0,
#     "solver": "lbfgs",
#     "note": (
#         "Model dilatih untuk kategori job_category paling kerucut. "
#         "SMOTE tidak digunakan. class_weight=None dipakai supaya kelas kecil tidak terlalu agresif."
#     )
# }

# metrics_path = os.path.join(OUTPUT_DIR, "model_metrics.json")

# with open(metrics_path, "w", encoding="utf-8") as f:
#     json.dump(metrics, f, indent=2, ensure_ascii=False)

# print("\n[SISTEM] Metrics berhasil disimpan:")
# print(metrics_path)


# =========================
# 7. ZIP ULANG SUPAYA MODEL DAN REPORT IKUT MASUK
# =========================

# zip_path = OUTPUT_DIR + ".zip"

# if os.path.exists(zip_path):
#     os.remove(zip_path)

# shutil.make_archive(OUTPUT_DIR, "zip", OUTPUT_DIR)

# print("\n[SISTEM] ZIP final berhasil dibuat:")
# print(zip_path)


# =========================
# 8. DOWNLOAD ZIP FINAL
# =========================

# files.download(zip_path)